### PR TITLE
NemesisRE's changes

### PR DESCRIPTION
**Pull request by faceleg**

### CODE REVIEW

**Comment by rhysd** [comment]
I can't read an intent of this PR. Please describe it.

**Comment by faceleg** [comment]
Your version doesn't work for me - it attempts to update my bundles each time vim opens (even after adding the autocmd as described in the doc).

Checking out @NemesisRE's branch solved this.

In the interest of maintaining "one true repo", I forked @NemesisRE's branch and opened this PR.

**Comment by rhysd** [comment]
OK, thanks.

**Comment by faceleg** [comment]
:dancer:

**Comment by NemesisRE** [comment]
seems like I don't need my fork anymore :)

**Comment by rhysd** [comment]
:dancers:

**Pull request merged**
